### ISSUE TITLE
Multiple Category Select Error

### ISSUE THREAD

**Issue by eric-kimbrel** [Microsoft/PowerBI-visuals-AttributeSlicer#39]
Issue seen on the switch-to-filtering branch.  

Add two items (categories) to the attribute slicer and select a row.   Filter is not applied to other visuals and an error is shown in the java script console.

```
powerbiportal.common.bundle.js:25414 UnhandledAngularException: Cannot read property 'findProperty' of undefined (caused by "undefined")
TypeError: Cannot read property 'findProperty' of undefined
    at SQColumnRefExpr.SQExpr.getConceptualProperty (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:23684:25)
    at SQColumnRefExpr.SQExpr.getMetadataForProperty (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:23789:37)
    at SQColumnRefExpr.SQExpr.getMetadata (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:23619:33)
    at SQExprValidationVisitor.validateCompatibleType (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:25369:41)
    at SQExprValidationVisitor.visitIn (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:25189:34)
    at SQInExpr.accept (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:24182:32)
    at SemanticQueryRewriter.rewriteWhere (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:26437:105)
    at SemanticFilter.rewrite (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:27290:38)
    at SemanticFilter.validate (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.dependencies.bundle.js:27295:22)
    at FilterGenerator.shouldApplyFilter (https://msit.powerbi.com/13.0.1700.2253/scripts/powerbiportal.explore.bundle.js:9725:43)
```

**Comment by eric-kimbrel** [comment]
This error only occurs if there is at least one other component on the screen.
